#!/usr/bin/env python3
"""
Generate the per-action "Learn more" docs from the committed connector
definitions plus a curated content table.

Every operation's externalDocs / "Learn more:" URL (stamped by gen_swagger.py,
hand-stamped for sdp-cmdb-v1) points at connectors/<name>/actions/<kebab>.md.
This script emits those pages: the parameter tables and response field lists
are derived mechanically from apiDefinition.swagger.json (so no parameter can
be missed), while the explanations and input_data example variations come from
the curated CONTENT table below.

Grounding for the curated claims:
  - envelope grammar (list_info keys, search_criteria conditions/aliases,
    logical_operator, children, value vs values, epoch-ms dates) — official
    on-prem V3 docs (getting-started/input-data.html, search-criteria.html);
  - note / worklog / closure_info payload fields — official on-prem V3 docs
    (requests/request_note.html, releases/release_worklog.html for the shared
    worklog object, requests/request.html);
  - live behaviour — this repo's docs/test-evidence/ captures and LESSONS.md.

Run:  python tools/gen_action_docs.py
Regenerate after changing any operation or content entry; the generated
markdown is the committed artifact, same policy as the definitions.
tools/check_action_docs.py (CI) fails if definitions and docs drift apart.
"""
import json
import os
import sys

from gen_swagger import kebab

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
REPO = "https://github.com/PBNZ/sdp-on-prem-powerplatform"
OFFICIAL = "https://www.manageengine.com/products/service-desk/sdpop-v3-api/"

GENERATED_MARK = ("<!-- Generated by tools/gen_action_docs.py - edit the "
                  "content table there and regenerate; do not edit by hand. -->")

# ---------------------------------------------------------------------------
# Shared explanation blocks (V3)
# ---------------------------------------------------------------------------

JSON_RULES = """\
### Formatting rules

- **One line of valid JSON.** Paste the whole envelope as a single line. JSON syntax only:
  **double quotes** around every key and string value, no trailing commas, no comments.
- **IDs are strings.** SDP returns its numeric IDs as JSON strings; send them the same way —
  `{"id":"1234"}`.
- **Reference fields take an object**, addressed by any unique key you have:
  `{"name":"High"}`, `{"id":"301"}`, or — for people — `{"email_id":"tech@company.com"}`.
- **Dates and times are epoch milliseconds (UTC).** Payload date fields are objects like
  `{"value":"1735689600000"}` (2025-01-01T00:00:00Z); inside `search_criteria` the value is the
  bare digit string.
- **Building the JSON in a flow:** dynamic content is spliced in as plain text, so the result
  must still be valid JSON. For free text that may contain quotes/newlines, sanitize first
  (e.g. `replace(<text>, '"', '\\"')` after doubling backslashes), or assemble the payload with
  a **Compose**/`json()` step and `string()` it into the parameter."""

CONDITIONS_TABLE = """\
### The condition catalogue

All conditions supported by `search_criteria` (official on-prem reference), with their
shorthand aliases:

| Condition | Aliases | Typical use |
|---|---|---|
| `is` | `=`, `eq` | exact match (strings, numbers, booleans, `{"id":...}` objects) |
| `is not` | `!=`, `neq` | exclusion |
| `greater than` | `gt` | numbers, epoch-ms dates |
| `greater or equal` | `gte` | numbers, epoch-ms dates |
| `lesser than` | `lt` | numbers, epoch-ms dates |
| `lesser or equal` | `lte` | numbers, epoch-ms dates |
| `between` / `not between` | — | ranges; pass the two bounds in `values` |
| `starts with` / `ends with` | — | text |
| `contains` / `not contains` | — | text |

Field paths use dot notation for sub-fields (`status.name`, `priority.name`,
`requester.email_id`). Two equivalent filter shapes work: a dotted field with a plain value
(`"field":"status.name","condition":"is","value":"Open"`) or the parent field with an object
value (`"field":"status","condition":"is","value":{"name":"Open"}`)."""

LIST_INFO_KEYS = """\
### Keys `list_info` supports

Verified against the official on-prem `input_data` reference:

| Key | Type | Meaning |
|---|---|---|
| `row_count` | int | rows to return — **maximum 100 per call** |
| `start_index` | int | index of the first row, for paging |
| `sort_field` | string | field to sort by (a field you see in the response) |
| `sort_order` | string | `"asc"` or `"desc"` |
| `get_total_count` | bool | adds `total_count` to the response `list_info` (default `false`) |
| `search_criteria` | object / array | filter conditions — see the variations below |
| `fields_required` | array | trim the response to just these fields |

The response echoes a `list_info` with `has_more_rows` (and `total_count` if you asked) —
loop with a growing `start_index` while `has_more_rows` is `true`."""


def list_info_section(default_json, module_examples, child_note=None):
    """The full list_info tutorial, with module-specific filter examples."""
    out = ["""## The `input_data` envelope — every variation

This action sends `input_data` as a **URL query parameter** holding a `list_info` JSON
envelope. The connector URL-encodes it for you — just paste JSON. Leave the box empty (or keep
the preset default) for SDP's defaults."""]
    if child_note:
        out.append(child_note)
    out += [JSON_RULES, LIST_INFO_KEYS, """\
### Variation 1 — plain paging

```json
{"list_info":{"row_count":25,"start_index":1}}
```

Page 2 is `"start_index":26`, and so on. Add `"get_total_count":true` on the first call to
size the loop:

```json
{"list_info":{"row_count":25,"start_index":1,"get_total_count":true}}
```

### Variation 2 — sorting

```json
{"list_info":{"row_count":25,"sort_field":"created_time","sort_order":"desc"}}
```
""", "### Variation 3 — filtering with `search_criteria`\n\n" + module_examples,
        CONDITIONS_TABLE, """\
### Variation 4 — multiple values (IN-style)

Use `values` (plural) with a list:

```json
{"list_info":{"row_count":50,"search_criteria":{"field":"priority.name","condition":"is","values":["High","Urgent"]}}}
```

### Variation 5 — combining criteria with AND / OR

`search_criteria` can be an **array**; every entry after the first carries a
`logical_operator` (`"AND"` or `"OR"`):

```json
{"list_info":{"search_criteria":[
  {"field":"status.name","condition":"is","value":"Open"},
  {"field":"priority.name","condition":"is","value":"High","logical_operator":"AND"}
]}}
```

### Variation 6 — grouped (nested) criteria with `children`

`children` nests sub-criteria under a parent, i.e. parentheses. This means
*status is Open AND (created after 2025-01-01)*:

```json
{"list_info":{"search_criteria":{
  "field":"status.name","condition":"is","value":"Open",
  "children":[{"field":"created_time","condition":"greater than","value":"1735689600000","logical_operator":"AND"}]
}}}
```

### Variation 7 — date windows

Dates in criteria are **epoch milliseconds as digit strings** (UTC). A window uses `between`
with both bounds in `values` — this is 2025-01-01 to 2025-07-01:

```json
{"list_info":{"search_criteria":{"field":"created_time","condition":"between","values":["1735689600000","1751328000000"]}}}
```

Power Automate tip for "now" in epoch ms:
`div(sub(ticks(utcNow()), ticks('1970-01-01T00:00:00Z')), 10000)`.

### Variation 8 — only the fields you need

```json
{"list_info":{"row_count":100,"fields_required":["id","subject","status"]}}
```
"""]
    if default_json:
        out.append("The parameter's preset default is:\n\n```json\n" + default_json + "\n```")
    return "\n\n".join(out)


CHILD_LIST_NOTE = """\
> This parameter is **optional** — leave it blank to get the default page. It accepts the
> paging keys below; there is normally no need to filter a per-request child list."""

FORM_INTRO = """\
This action sends `input_data` as a **form field** (`application/x-www-form-urlencoded`
body) — the connector does the encoding, you paste plain JSON, exactly like the query-string
variant on the list actions."""

V3_AUTH = """\
## Authentication

Nothing to do per action: the connection you created for this connector sends the technician
API key on every call as the `authtoken` header (a secured connection parameter — it never
lives in a flow or in the definition). Generate keys in SDP under *Admin → Technicians →
Generate API Key*, ideally for a least-privilege integration technician. The repo
[README](../../../README.md) covers key scoping and the HTTPS-only rule."""

V1_AUTH = """\
## Authentication

The connection sends the technician key on every call as the `TECHNICIAN_KEY` **query
parameter** (secured connection parameter; same secret value as the V3 `authtoken`). Because
it travels in the URL, **HTTPS is mandatory** and the key should be scoped tightly — see the
[connector README](../README.md#whats-different-about-v1)."""

ACCEPT_NOTE = """\
Fixed technical header, preset to `application/vnd.manageengine.sdp.v3+json` — it selects
SDP's V3 media type (and, for worklogs, the current V3 worklog format). It is marked
*internal*, so the designer hides it from makers; you'll only see it in the connector's code
view. Leave it as is, including `required: true` — Power Platform silently drops optional
internal headers (see the repo's [LESSONS.md](../../../LESSONS.md))."""

V3_RESPONSE_STATUS = """\
Success means `response_status.status_code` **2000** — check that, not just HTTP 200. One
shape wobble to handle in flows: on **list** successes `response_status` is an **array** of
status objects, on **single-resource and error** responses it's an **object**. The connector
deliberately leaves it untyped; branch on `Array.isArray`-style logic (e.g. Power Automate
`first(...)` when it's an array)."""

WRITE_CAVEAT = """\
**Write-verification status:** this operation is authored from the official API contract and
a working client, and it validates structurally, but it has **not been live write-tested yet**
(the repo's reads are live-verified; writes await a disposable instance — see
[CHECKPOINT.md](../../../CHECKPOINT.md)). Test against a throwaway SDP first, **never against
a production instance or the read-only public demo**."""

ID_FROM_LIST = ("Numeric ID as a string. Take it from a matching List action's output "
                "(dynamic content `id`) or from the record's URL in the SDP UI.")


def official_ref(label, page):
    return (label, OFFICIAL + page)


REF_INPUT_DATA = official_ref("Official reference — the input_data envelope",
                              "getting-started/input-data.html")
REF_SEARCH = official_ref("Official reference — search_criteria grammar",
                          "getting-started/search-criteria.html")
REF_REQUEST = official_ref("Official reference — Request API", "requests/request.html")
REF_NOTE = official_ref("Official reference — Request Note API", "requests/request_note.html")
REF_WORKLOG = official_ref("Official reference — the V3 worklog object (documented under "
                           "Releases; requests use the same worklog format)",
                           "releases/release_worklog.html")
REF_CHANGE = official_ref("Official reference — Change API", "changes/change.html")
EV_PHASE1 = ("Live evidence — phase 1 reads (demo)",
             "../../../docs/test-evidence/phase1-reads.txt")
EV_PHASE2 = ("Live evidence — phase 2 reads (demo)",
             "../../../docs/test-evidence/phase2-reads.txt")
EV_PHASE3 = ("Live evidence — Execute Query behaviour (demo)",
             "../../../docs/test-evidence/phase3-execute-query.txt")

VERIFIED_READ = "Read operation, **live-verified** on the public demo (HTTP 200, status_code 2000)."
VERIFIED_MODELED = ("Modeled from the official API contract and a working client; "
                    "live verification on a matching build is still pending.")

# ---------------------------------------------------------------------------
# Curated per-operation content
# ---------------------------------------------------------------------------

def entry(intro, input_data=None, params=None, response=None, gotchas=(), refs=(),
          verified=VERIFIED_READ):
    return {"intro": intro, "input_data": input_data, "params": params or {},
            "response": response, "gotchas": list(gotchas), "refs": list(refs),
            "verified": verified}


REQ_FILTERS = """\
One criterion filters the list. Module examples (shipped default uses the first):

```json
{"list_info":{"row_count":10,"start_index":1,"get_total_count":true,"search_criteria":{"field":"status.name","condition":"is","value":"Open"}}}
```

```json
{"list_info":{"row_count":50,"search_criteria":{"field":"requester.email_id","condition":"is","value":"user@company.com"}}}
```

```json
{"list_info":{"row_count":50,"search_criteria":{"field":"subject","condition":"contains","value":"printer"}}}
```"""

CHG_FILTERS = """\
One criterion filters the list — change-module examples:

```json
{"list_info":{"row_count":50,"search_criteria":{"field":"stage.name","condition":"is","value":"Implementation"}}}
```

```json
{"list_info":{"row_count":50,"search_criteria":{"field":"change_type.name","condition":"is","value":"Normal"}}}
```"""

PRB_FILTERS = """\
One criterion filters the list — problem-module examples:

```json
{"list_info":{"row_count":50,"search_criteria":{"field":"title","condition":"contains","value":"VPN"}}}
```

```json
{"list_info":{"row_count":50,"search_criteria":{"field":"priority.name","condition":"is","value":"High"}}}
```"""

SOL_FILTERS = """\
One criterion filters the list — solution-module examples:

```json
{"list_info":{"row_count":50,"search_criteria":{"field":"topic.name","condition":"is","value":"Network"}}}
```

```json
{"list_info":{"row_count":50,"search_criteria":{"field":"title","condition":"contains","value":"reset"}}}
```"""

ASSET_FILTERS = """\
One criterion filters the list — asset examples:

```json
{"list_info":{"row_count":50,"search_criteria":{"field":"asset_state.name","condition":"is","value":"In Use"}}}
```

```json
{"list_info":{"row_count":50,"search_criteria":{"field":"name","condition":"contains","value":"web"}}}
```"""

CI_FILTERS = """\
One criterion filters the list — CI examples:

```json
{"list_info":{"row_count":50,"search_criteria":{"field":"name","condition":"contains","value":"web01"}}}
```"""

LOOKUP_FILTER = """\
Lookups rarely need filtering, but the same grammar applies — e.g. name prefix:

```json
{"list_info":{"row_count":100,"search_criteria":{"field":"name","condition":"starts with","value":"Net"}}}
```"""

LOOKUP_DEFAULT = '{"list_info":{"row_count":100,"start_index":1,"get_total_count":true}}'
LIST_DEFAULT = '{"list_info":{"row_count":10,"start_index":1,"get_total_count":true}}'


def lookup_entry(what, extra_gotchas=(), extra_refs=()):
    intro = (what + " Marked *advanced* in the designer: it exists to feed dropdowns and "
             "name→ID resolution when you assemble `input_data` payloads for the write "
             "actions, not as a primary action.")
    return entry(
        intro,
        input_data=list_info_section(LOOKUP_DEFAULT, LOOKUP_FILTER),
        response=("Items arrive in the `list` array as `{id, name}` pairs — use `name` for "
                  "display and either key in payload reference fields. More than 100 entries? "
                  "Page with `start_index`."),
        gotchas=list(extra_gotchas),
        refs=[REF_INPUT_DATA, REF_SEARCH, EV_PHASE1] + list(extra_refs))


CONTENT = {}

# --------------------------- sdp-service-desk ------------------------------

CONTENT["sdp-service-desk"] = {
    "ListRequests": entry(
        "Pages through service desk requests, optionally sorted and filtered server-side. "
        "This is the workhorse read: prefer a tight `search_criteria` over pulling pages and "
        "filtering in the flow.",
        input_data=list_info_section(
            '{"list_info":{"row_count":10,"start_index":1,"get_total_count":true,"search_criteria":{"field":"status.name","condition":"is","value":"Open"}}}',
            REQ_FILTERS),
        response=("Each entry in `requests` carries `id`, `subject`, `status.name`, "
                  "`priority.name`, `requester`, `technician`, `group`, `site`, "
                  "`created_time`/`due_by_time` (`display_value` + epoch-ms `value`) and "
                  "`is_overdue` — `id` is what the Get/Update/Close/Delete actions need."),
        refs=[REF_INPUT_DATA, REF_SEARCH, REF_REQUEST,
              ("Live evidence — list requests (demo)", "../../../docs/test-evidence/listrequests.txt")]),

    "GetRequest": entry(
        "Fetches the full detail of one request by ID — subject, description, status, "
        "priority, request type, requester, technician, group, site, and timestamps.",
        params={"request_id": ID_FROM_LIST + " Example: `32251`."},
        refs=[REF_REQUEST,
              ("Live evidence — get request (demo)", "../../../docs/test-evidence/getrequest.txt")]),

    "CreateRequest": entry(
        "Creates a new service desk request. Only `subject` is mandatory — everything else "
        "is optional and instance-dependent.",
        input_data=FORM_INTRO + """

The envelope wraps one `request` object.

### Variation 1 — minimal (the only mandatory field)

```json
{"request":{"subject":"Printer down"}}
```

### Variation 2 — typical: requester + priority (the shipped example)

```json
{"request":{"subject":"Printer down","requester":{"email_id":"user@company.com"},"priority":{"name":"High"}}}
```

### Variation 3 — richer create

`description` accepts HTML; reference fields go by `name`, `id`, or (people) `email_id`;
custom "user-defined fields" ride in `udf_fields` under their column names:

```json
{"request":{"subject":"Printer down","description":"<p>3rd floor HP is jammed</p>","requester":{"email_id":"user@company.com"},"priority":{"name":"High"},"status":{"name":"Open"},"udf_fields":{"udf_char1":"PO-1234"}}}
```

The official field list for the `request` object also includes `impact_details`, `resolution`
and more — but the exact catalogue (and which fields are mandatory) is **instance
configuration**, so mirror what your SDP's request form shows. Field-by-field shapes follow
the rules below.

""" + JSON_RULES,
        params={"input_data": "The `{\"request\":{...}}` JSON envelope — see the deep dive below."},
        response=("`201` (some builds `200`) with the created `request`, including its new "
                  "`id` — grab it from dynamic content for follow-up actions."),
        gotchas=["Mandatory fields beyond `subject` (templates, request forms) are instance "
                 "policy; a create that violates them is rejected with a 4xxx status_code."],
        refs=[REF_REQUEST, REF_INPUT_DATA], verified=WRITE_CAVEAT),

    "UpdateRequest": entry(
        "Partially updates a request: **only the fields you send change**, everything else "
        "stays as is.",
        input_data=FORM_INTRO + """

Same `request` object grammar as Create — send just the deltas.

### Variation 1 — bump priority and move status (the shipped example)

```json
{"request":{"priority":{"name":"High"},"status":{"name":"In Progress"}}}
```

### Variation 2 — assign a technician and group

```json
{"request":{"technician":{"email_id":"tech@company.com"},"group":{"name":"Network"}}}
```

### Variation 3 — update a custom field

```json
{"request":{"udf_fields":{"udf_char1":"PO-5678"}}}
```

""" + JSON_RULES,
        params={"request_id": ID_FROM_LIST,
                "input_data": "The partial `{\"request\":{...}}` envelope — deep dive below."},
        gotchas=["Status transitions can be gated by workflow rules/mandatory fields; a "
                 "blocked transition comes back as a 4xxx status_code, not an HTTP error."],
        refs=[REF_REQUEST], verified=WRITE_CAVEAT),

    "DeleteRequest": entry(
        "Moves a request to the SDP **trash** (from where an admin can restore or purge it). "
        "No `input_data` — the request ID in the path is everything.",
        params={"request_id": ID_FROM_LIST},
        response="`200` (some paths `204`) with an SDP status envelope; no request body returns.",
        gotchas=["Destructive. Point this only at instances you own; the public demo is "
                 "read-only by policy for this repo."],
        refs=[REF_REQUEST], verified=WRITE_CAVEAT),

    "CloseRequest": entry(
        "Closes a request, optionally recording closure details. Distinct from Update: this "
        "drives SDP's close semantics (closure code, requester acknowledgement).",
        input_data=FORM_INTRO + """

The envelope wraps `request.closure_info`. All four official fields:

| Field | Type | Meaning |
|---|---|---|
| `closure_comments` | string | free-text close-out note |
| `closure_code` | object | admin-defined catalogue value, e.g. `{"name":"Success"}` |
| `requester_ack_resolution` | bool | requester confirmed the resolution |
| `requester_ack_comments` | string | the requester's own words |

### Variation 1 — comments only

```json
{"request":{"closure_info":{"closure_comments":"Resolved by replacing the toner"}}}
```

### Variation 2 — with a closure code (the shipped example)

```json
{"request":{"closure_info":{"closure_comments":"Resolved","closure_code":{"name":"Success"}}}}
```

### Variation 3 — full acknowledgement

```json
{"request":{"closure_info":{"requester_ack_resolution":true,"requester_ack_comments":"Working again, thanks","closure_comments":"Reset the password","closure_code":{"name":"Success"}}}}
```

`closure_code` names come from your instance's closure-code catalogue (*Admin*), so use one
that exists there.

""" + JSON_RULES,
        params={"request_id": ID_FROM_LIST,
                "input_data": "The `closure_info` envelope — deep dive below. May be empty "
                              "JSON `{}` if your close rules require nothing."},
        gotchas=["Close can be blocked by instance rules: unfilled mandatory fields, open "
                 "tasks, or resolution requirements surface as a 4xxx status_code."],
        refs=[REF_REQUEST], verified=WRITE_CAVEAT),

    "ListRequestNotes": entry(
        "Lists the notes on one request, newest coverage via paging.",
        input_data=list_info_section(None, """\
Child lists rarely need filters, but the same grammar applies — e.g. notes added after
2025-01-01:

```json
{"list_info":{"search_criteria":{"field":"created_time","condition":"greater than","value":"1735689600000"}}}
```""", child_note=CHILD_LIST_NOTE),
        params={"request_id": ID_FROM_LIST},
        response="`notes[]` items carry `id`, `description`, `created_time`, `show_to_requester`.",
        refs=[REF_NOTE, EV_PHASE1]),

    "AddRequestNote": entry(
        "Adds a note to a request — the bread-and-butter write for flow automations "
        "(acknowledgements, bot annotations, cross-system links).",
        input_data=FORM_INTRO + """

The envelope wraps one `note` object. Official field set:

| Field | Type | Meaning |
|---|---|---|
| `description` | string | the note body (required in practice — an empty note is pointless) |
| `show_to_requester` | bool | `false` = technician-only note (default behaviour), `true` = requester sees it |
| `mark_first_response` | bool | count this note as the request's first response — only allowed while the request has no response yet |
| `add_to_linked_requests` | bool | replicate the note onto linked requests (only at add time) |

### Variation 1 — private technician note (the shipped example)

```json
{"note":{"description":"Called the user","show_to_requester":false}}
```

### Variation 2 — requester-visible note

```json
{"note":{"description":"We have ordered the replacement part.","show_to_requester":true}}
```

### Variation 3 — first response + fan-out to linked requests

```json
{"note":{"description":"Acknowledged - investigating.","show_to_requester":true,"mark_first_response":true,"add_to_linked_requests":true}}
```

""" + JSON_RULES,
        params={"request_id": ID_FROM_LIST + " Example: `32251`.",
                "input_data": "The `{\"note\":{...}}` envelope — all fields and variations below."},
        response="`201` (some builds `200`) with the created `note`, including its `id`.",
        refs=[REF_NOTE], verified=WRITE_CAVEAT),

    "ListRequestWorklogs": entry(
        "Lists the worklogs (time entries) recorded on one request.",
        input_data=list_info_section(None, """\
Child lists rarely need filters, but the same grammar applies — e.g. by description text:

```json
{"list_info":{"search_criteria":{"field":"description","condition":"contains","value":"patch"}}}
```""", child_note=CHILD_LIST_NOTE),
        params={"request_id": ID_FROM_LIST},
        response="`worklogs[]` items carry `id`, `description`, and the `owner` (id/name/email).",
        refs=[REF_WORKLOG, EV_PHASE1]),

    "AddRequestWorklog": entry(
        "Records a worklog (time entry) on a request.",
        input_data=FORM_INTRO + """

The envelope wraps one `worklog` object. The V3 worklog object (official on-prem reference —
the same worklog format SDP's current builds expect when the connector's `Accept` header is
in place):

| Field | Type | Meaning |
|---|---|---|
| `owner` | user object | **mandatory** — who did the work: `{"email_id":...}`, `{"id":...}` or `{"name":...}` |
| `description` | string | what was done |
| `start_time` / `end_time` | datetime object | `{"value":"<epoch ms>"}` |
| `time_spent` | object | `{"hours":"2","minutes":"30"}` — alternative to start/end |
| `type` | object | worklog type from your instance's catalogue, `{"name":...}` or `{"id":...}` |
| `other_cost` | number-string | extra cost beyond the owner's rate |
| `include_nonoperational_hours` | bool | count time outside operational hours |
| `mark_first_response` | bool | count this as the first response |

### Variation 1 — minimal (the shipped example)

```json
{"worklog":{"description":"Investigated the issue","owner":{"email_id":"tech@company.com"}}}
```

### Variation 2 — clocked interval

```json
{"worklog":{"description":"On-site fix","owner":{"email_id":"tech@company.com"},"start_time":{"value":"1735689600000"},"end_time":{"value":"1735696800000"}}}
```

### Variation 3 — explicit time spent, typed, with extra cost

```json
{"worklog":{"description":"After-hours patch","owner":{"id":"4"},"time_spent":{"hours":"2","minutes":"30"},"type":{"id":"1"},"other_cost":"0","include_nonoperational_hours":true}}
```

""" + JSON_RULES,
        params={"request_id": ID_FROM_LIST,
                "input_data": "The `{\"worklog\":{...}}` envelope — all fields and variations below."},
        response="`201` (some builds `200`) with the created `worklog` and its `id`.",
        refs=[REF_WORKLOG], verified=WRITE_CAVEAT),

    "ListRequestTasks": entry(
        "Lists the tasks attached to one request.",
        input_data=list_info_section(None, """\
Child lists rarely need filters, but the same grammar applies — e.g. by task title:

```json
{"list_info":{"search_criteria":{"field":"title","condition":"contains","value":"deploy"}}}
```""", child_note=CHILD_LIST_NOTE),
        params={"request_id": ID_FROM_LIST},
        response="`tasks[]` items carry `id`, `title`, `status.name`.",
        refs=[official_ref("Official reference — Request Task API", "requests/request_task.html"),
              EV_PHASE1]),

    "GetRequestResolution": entry(
        "Reads the resolution recorded on a request. Note there is deliberately **no "
        "input_data parameter** on this action: SDP rejects the whole call with a 400/4000 if "
        "one is attached to this endpoint (single-object read).",
        params={"request_id": ID_FROM_LIST},
        response=("`resolution.content` is the text (HTML) — it is `null` when no resolution "
                  "has been set, so null-check before using it."),
        refs=[REF_REQUEST, EV_PHASE1]),

    "AddRequestResolution": entry(
        "Sets (or replaces) the resolution of a request.",
        input_data=FORM_INTRO + """

The envelope wraps one `resolution` object with its `content`:

### Variation 1 — plain text (the shipped example)

```json
{"resolution":{"content":"Replaced the toner cartridge."}}
```

### Variation 2 — HTML content

```json
{"resolution":{"content":"<p>Replaced the toner cartridge.</p><ul><li>Part: HP 26A</li></ul>"}}
```

""" + JSON_RULES,
        params={"request_id": ID_FROM_LIST,
                "input_data": "The `{\"resolution\":{\"content\":...}}` envelope — below."},
        refs=[REF_REQUEST], verified=WRITE_CAVEAT),

    # Changes ---------------------------------------------------------------
    "ListChanges": entry(
        "Pages through change requests with the standard envelope.",
        input_data=list_info_section(LIST_DEFAULT, CHG_FILTERS),
        response=("`changes[]` items carry `id`, `title`, `status.name`, `stage.name`, "
                  "`change_type.name`, `priority`, `change_owner`, `group`, `site`, "
                  "`created_time`."),
        refs=[REF_INPUT_DATA, REF_SEARCH, REF_CHANGE, EV_PHASE1]),

    "CreateChange": entry(
        "Creates a change. `title` is the required field.",
        input_data=FORM_INTRO + """

The envelope wraps one `change` object; reference fields follow the same
name/id shapes as requests.

### Variation 1 — minimal

```json
{"change":{"title":"Upgrade DB server"}}
```

### Variation 2 — typed change (the shipped example)

```json
{"change":{"title":"Upgrade DB server","change_type":{"name":"Normal"}}}
```

### Variation 3 — with owner and description

```json
{"change":{"title":"Upgrade DB server","change_type":{"name":"Normal"},"change_owner":{"email_id":"tech@company.com"},"description":"<p>Postgres 15 to 16</p>"}}
```

The full `change` field catalogue (roles, CAB, stages, templates) is instance configuration —
see the official Change API reference below.

""" + JSON_RULES,
        params={"input_data": "The `{\"change\":{...}}` envelope — variations below."},
        response="`201`/`200` with the created `change`, including `id` and initial `stage`.",
        refs=[REF_CHANGE], verified=WRITE_CAVEAT),

    "GetChange": entry(
        "Fetches one change by ID.",
        params={"change_id": ID_FROM_LIST},
        refs=[REF_CHANGE, EV_PHASE1]),

    "UpdateChange": entry(
        "Partially updates a change — only sent fields move.",
        input_data=FORM_INTRO + """

### Variation 1 — advance the stage (the shipped example)

```json
{"change":{"stage":{"name":"Implementation"}}}
```

### Variation 2 — reassign and reprioritise

```json
{"change":{"change_owner":{"email_id":"tech@company.com"},"priority":{"name":"High"}}}
```

""" + JSON_RULES,
        params={"change_id": ID_FROM_LIST,
                "input_data": "The partial `{\"change\":{...}}` envelope — below."},
        gotchas=["Stage transitions are workflow-gated in most instances (approvals, CAB); "
                 "a blocked move returns a 4xxx status_code.", WRITE_CAVEAT],
        refs=[REF_CHANGE], verified=WRITE_CAVEAT),

    # Problems ----------------------------------------------------------------
    "ListProblems": entry(
        "Pages through problems with the standard envelope.",
        input_data=list_info_section(LIST_DEFAULT, PRB_FILTERS),
        response="`problems[]` items carry `id`, `title`, `status.name`, `priority`, `technician`.",
        refs=[REF_INPUT_DATA, REF_SEARCH, EV_PHASE1]),

    "CreateProblem": entry(
        "Creates a problem. `title` is the required field.",
        input_data=FORM_INTRO + """

### Variation 1 — minimal (the shipped example)

```json
{"problem":{"title":"Recurring VPN drops"}}
```

### Variation 2 — with description and priority

```json
{"problem":{"title":"Recurring VPN drops","description":"<p>Multiple sites since Monday</p>","priority":{"name":"High"}}}
```

""" + JSON_RULES,
        params={"input_data": "The `{\"problem\":{...}}` envelope — below."},
        verified=WRITE_CAVEAT),

    "GetProblem": entry(
        "Fetches one problem by ID.",
        params={"problem_id": ID_FROM_LIST},
        refs=[EV_PHASE1]),

    "UpdateProblem": entry(
        "Partially updates a problem.",
        input_data=FORM_INTRO + """

### Variation 1 — close it (the shipped example)

```json
{"problem":{"status":{"name":"Closed"}}}
```

### Variation 2 — hand it to a technician

```json
{"problem":{"technician":{"email_id":"tech@company.com"},"priority":{"name":"Medium"}}}
```

""" + JSON_RULES,
        params={"problem_id": ID_FROM_LIST,
                "input_data": "The partial `{\"problem\":{...}}` envelope — below."},
        verified=WRITE_CAVEAT),

    # Solutions ---------------------------------------------------------------
    "ListSolutions": entry(
        "Pages through knowledge-base solution articles.",
        input_data=list_info_section(LIST_DEFAULT, SOL_FILTERS),
        response="`solutions[]` items carry `id`, `title`, `topic.name`, `created_time`.",
        refs=[REF_INPUT_DATA, REF_SEARCH, EV_PHASE1,
              ("V3 Solutions API changes (official note)",
               "https://help.servicedeskplus.com/v3-solutions-api-changes")]),

    "CreateSolution": entry(
        "Creates a solution article. `title` is the required field.",
        input_data=FORM_INTRO + """

### Variation 1 — the shipped example

```json
{"solution":{"title":"How to reset VPN","description":"Steps...","topic":{"name":"Network"}}}
```

### Variation 2 — HTML body

```json
{"solution":{"title":"How to reset VPN","description":"<ol><li>Open the client</li><li>Reset profile</li></ol>","topic":{"name":"Network"}}}
```

""" + JSON_RULES,
        params={"input_data": "The `{\"solution\":{...}}` envelope — below."},
        verified=WRITE_CAVEAT),

    "GetSolution": entry(
        "Fetches one solution article by ID.",
        params={"solution_id": ID_FROM_LIST},
        refs=[EV_PHASE1]),

    "UpdateSolution": entry(
        "Partially updates a solution article.",
        input_data=FORM_INTRO + """

### Variation 1 — publish it (the shipped example)

```json
{"solution":{"is_public":true}}
```

### Variation 2 — retitle and re-topic

```json
{"solution":{"title":"How to reset the VPN profile","topic":{"name":"Network"}}}
```

""" + JSON_RULES,
        params={"solution_id": ID_FROM_LIST,
                "input_data": "The partial `{\"solution\":{...}}` envelope — below."},
        verified=WRITE_CAVEAT),

    # Lookups -----------------------------------------------------------------
    "ListTechnicians": lookup_entry("Lists technicians (id + name)."),
    "ListRequesters": lookup_entry(
        "Lists requesters / end users (id + name).",
        extra_gotchas=["**Build variance:** this action calls `/users` — the path verified "
                       "live on the demo build. Some builds expose `/requesters` instead; if "
                       "this 404s on your instance, repoint the path (edit the definition or "
                       "`tools/gen_swagger.py` and regenerate)."]),
    "ListCategories": lookup_entry("Lists request categories (id + name)."),
    "ListStatuses": lookup_entry("Lists request statuses (id + name) — feed status names "
                                 "into request `search_criteria` and updates."),
    "ListPriorities": lookup_entry("Lists priority levels (id + name)."),
    "ListSites": lookup_entry("Lists sites / locations (id + name)."),
    "ListSupportGroups": lookup_entry(
        "Lists technician support groups (id + name).",
        extra_gotchas=["**Build variance:** this action calls `/support_groups` (verified "
                       "live on the demo). Some builds expose `/groups` instead; repoint the "
                       "path if it 404s on yours."]),
    "ListDepartments": lookup_entry("Lists departments (id + name)."),
    "ListUrgencies": lookup_entry("Lists urgency levels (id + name)."),
    "ListImpacts": lookup_entry("Lists impact levels (id + name)."),
    "ListModes": lookup_entry("Lists request submission modes (id + name)."),
    "ListRequestTypes": lookup_entry("Lists request types, e.g. Incident vs Service Request "
                                     "(id + name)."),
}

# --------------------------- sdp-assets-cmdb-v3 ----------------------------

CI_TYPE_NOTE = ("**The CI type's `api_plural_name`** — not its display name. Get it from "
                "*List CI types* (e.g. `cmdb_businessservice`). Plural names vary per "
                "instance, so resolve them at runtime rather than hard-coding.")

CONTENT["sdp-assets-cmdb-v3"] = {
    "ListCITypes": entry(
        "Lists every CMDB configuration-item type. The key output is each type's "
        "`api_plural_name` — the value the per-type CI actions take as their **CI Type** path "
        "parameter.",
        input_data=list_info_section(
            '{"list_info":{"row_count":100,"start_index":1,"get_total_count":true}}',
            LOOKUP_FILTER.replace('"name"', '"display_name"').replace("Net", "Business")),
        response=("`ci_types[]` items carry `id`, `display_name`, `description` and the "
                  "all-important `api_plural_name`."),
        refs=[REF_INPUT_DATA, EV_PHASE2]),

    "ListAllCIs": entry(
        "Lists configuration items across **every** type — the cross-CMDB view.",
        input_data=list_info_section(LIST_DEFAULT, CI_FILTERS),
        response="`cmdb[]` items carry `id`, `name`, and the CI's `ci_type`.",
        refs=[REF_INPUT_DATA, REF_SEARCH, EV_PHASE2]),

    "ListCIsByType": entry(
        "Lists the configuration items of **one** type.",
        input_data=list_info_section(LIST_DEFAULT, CI_FILTERS),
        params={"ci_type": CI_TYPE_NOTE},
        response="`cmdb[]` items carry `id`, `name`, `ci_type`.",
        gotchas=["Enter a real plural name from *List CI types* — literals like `assets` or "
                 "`cmdb` are different endpoints with their own actions."],
        refs=[REF_INPUT_DATA, REF_SEARCH, EV_PHASE2]),

    "CreateCI": entry(
        "Creates a configuration item of the given type.",
        input_data=FORM_INTRO + """

The envelope wraps one `ci` object. The attribute set is **type-specific** — fetch it first
with *Get CI type metadata*.

### Variation 1 — the shipped example

```json
{"ci":{"name":"web01","ci_type":{"name":"Business Service"}}}
```

### Variation 2 — with type-specific attributes

Attribute names come from the type's metadata; reference attributes use the usual
`{"name":...}` / `{"id":...}` object shapes:

```json
{"ci":{"name":"web01","ci_type":{"name":"Business Service"},"description":"Customer portal","site":{"name":"HQ"}}}
```

""" + JSON_RULES,
        params={"ci_type": CI_TYPE_NOTE,
                "input_data": "The `{\"ci\":{...}}` envelope — see below and the type's metadata."},
        refs=[EV_PHASE2], verified=WRITE_CAVEAT),

    "GetCI": entry(
        "Fetches one configuration item by type + numeric ID.",
        params={"ci_type": CI_TYPE_NOTE,
                "ci_id": "Numeric CI ID as a string — from *List CIs by type* / *List all CIs*."},
        refs=[EV_PHASE2]),

    "UpdateCI": entry(
        "Updates a configuration item by type + ID. V3 CMDB updates **by CI ID only** — the "
        "legacy criteria-based bulk update does not exist here.",
        input_data=FORM_INTRO + """

### Variation 1 — rename (the shipped example)

```json
{"ci":{"name":"web01-renamed"}}
```

### Variation 2 — update type-specific attributes

```json
{"ci":{"description":"Customer portal (decommission planned)","site":{"name":"DR"}}}
```

""" + JSON_RULES,
        params={"ci_type": CI_TYPE_NOTE,
                "ci_id": "Numeric CI ID as a string.",
                "input_data": "The partial `{\"ci\":{...}}` envelope — below."},
        refs=[EV_PHASE2], verified=WRITE_CAVEAT),

    "GetCITypeMetadata": entry(
        "Returns the field/layout metadata of a CI type — the authoritative attribute list "
        "for building Create/Update CI payloads. Deliberately has **no input_data "
        "parameter**: SDP rejects this endpoint with 400/4000 if one is attached.",
        params={"ci_type": CI_TYPE_NOTE},
        response="A `metadata` object describing the type's fields and layout.",
        refs=[EV_PHASE2]),

    "ListCIRelationships": entry(
        "Lists a CI's association relationships (upstream/downstream links). Requires SDP "
        "build **15100+** (this V3 endpoint is the reason the separate V1 legacy connector "
        "exists for older builds).",
        input_data="""## The `input_data` filter (optional)

Leave blank for all associations, or pass the association filter (the shape used live on the
demo):

```json
{"list_info":{"filter":{"name":"get_all_association"}}}
```

""" + JSON_RULES,
        params={"ci_type": CI_TYPE_NOTE,
                "ci_id": "Numeric CI ID as a string."},
        response="`assoc_ci_relationships[]` items carry `id` and `relationship_type`.",
        refs=[EV_PHASE2]),

    "AddCIRelationship": entry(
        "Adds an association relationship to a CI (build **15100+**).",
        input_data=FORM_INTRO + """

The envelope wraps one `assoc_ci_relationship`, pointing at the far CI and the relationship
type (IDs from *List CI relationships* / the relationship-type catalogue — the
`templates/05-relationship-types.sql` query in this repo lists them via the Query connector):

```json
{"assoc_ci_relationship":{"end_ci":{"id":"123"},"relationship":{"id":"1"}}}
```

""" + JSON_RULES,
        params={"ci_type": CI_TYPE_NOTE,
                "ci_id": "Numeric CI ID (the near end of the relationship) as a string.",
                "input_data": "The `assoc_ci_relationship` envelope — above."},
        refs=[EV_PHASE2], verified=WRITE_CAVEAT),

    "ListAssetModules": entry(
        "Lists the asset type/module hierarchy (id + name pairs).",
        input_data=list_info_section(LIST_DEFAULT, LOOKUP_FILTER.replace("Net", "Work")),
        refs=[REF_INPUT_DATA, EV_PHASE2]),

    "ListAssets": entry(
        "Pages through the asset inventory.",
        input_data=list_info_section(LIST_DEFAULT, ASSET_FILTERS),
        response=("`assets[]` items carry `id`, `name`, `product_type`, `asset_state`, "
                  "`site`, `department`."),
        refs=[REF_INPUT_DATA, REF_SEARCH, EV_PHASE2]),

    "GetAsset": entry(
        "Fetches one asset by ID.",
        params={"asset_id": ID_FROM_LIST},
        refs=[EV_PHASE2]),

    "UpdateAsset": entry(
        "Partially updates an asset — only sent fields move.",
        input_data=FORM_INTRO + """

### Variation 1 — state change (the shipped example)

```json
{"asset":{"asset_state":{"name":"In Use"}}}
```

### Variation 2 — reassign location/department

```json
{"asset":{"site":{"name":"HQ"},"department":{"name":"Finance"}}}
```

""" + JSON_RULES,
        params={"asset_id": ID_FROM_LIST,
                "input_data": "The partial `{\"asset\":{...}}` envelope — below."},
        refs=[EV_PHASE2], verified=WRITE_CAVEAT),
}

# --------------------------- sdp-query -------------------------------------

CONTENT["sdp-query"] = {
    "ExecuteQuery": entry(
        "Runs **one read-only SQL SELECT** against the SDP database via the Execute Query "
        "report API and returns the rows. One good SELECT (JOINs, aggregates, custom fields) "
        "replaces many REST GET calls.",
        input_data=FORM_INTRO + """

The envelope has exactly one key — `query` — whose value is the SQL string.

### Formatting the SQL inside JSON

- **Alias every column with `AS`** — the response rows are keyed by the aliases; un-aliased
  expressions get unstable names.
- Keep the SQL on **one line** (or escape newlines as `\\n`); never leave raw line breaks
  inside the JSON string.
- SQL string literals use **single quotes**, which need no escaping in JSON — convenient. If
  you must embed a double quote (identifier quoting), escape it as `\\"`.

### Variation 1 — the capability probe (run this once at setup)

```json
{"query":"SELECT 1 AS test"}
```

If it errors, Execute Query is not available on this connection (permission / edition /
build) — fall back to the REST connectors.

### Variation 2 — recent requests with status (live-verified template 01)

```json
{"query":"SELECT wo.workorderid AS id, wo.title AS subject, sd.statusname AS status, wo.createdtime AS created_epoch_ms FROM workorder wo LEFT JOIN workorderstates ws ON wo.workorderid = ws.workorderid LEFT JOIN statusdefinition sd ON ws.statusid = sd.statusid ORDER BY wo.workorderid DESC LIMIT 20"}
```

### Variation 3 — aggregate: request count by status (template 02)

```json
{"query":"SELECT sd.statusname AS status, COUNT(*) AS total FROM workorder wo LEFT JOIN workorderstates ws ON wo.workorderid = ws.workorderid LEFT JOIN statusdefinition sd ON ws.statusid = sd.statusid GROUP BY sd.statusname ORDER BY total DESC"}
```

### Variation 4 — cross-module JOIN: requests to assets (template 07)

```json
{"query":"SELECT wta.workorderid AS request_id, wo.title AS subject, r.resourcename AS asset_name FROM workordertoasset wta JOIN workorder wo ON wta.workorderid = wo.workorderid JOIN resources r ON wta.assetid = r.resourceid ORDER BY wta.workorderid DESC LIMIT 25"}
```

All eight starter queries live in [`templates/`](../../../templates/) (build-14990 schema,
each verified to run live). **Physical table/column names are build-specific** — keep SQL in
flow variables or the templates library, not hard-baked, so an upgrade can't strand you.

""" + JSON_RULES,
        params={"input_data": "The `{\"query\":\"SELECT ...\"}` envelope — formats and "
                              "variations below."},
        response=("`execute_query.data` is an array of row objects **keyed by your SQL "
                  "aliases** (hence the `AS` rule). Empty result = empty array, still "
                  "status_code 2000."),
        gotchas=[
            "**SELECT only** — `UPDATE`/`DELETE`/`INSERT` are rejected server-side (4004), "
            "as are `information_schema`/catalog queries. **POST only** — a GET returns 4021 "
            "*Invalid HTTP method*. All verified live.",
            "Needs an **admin-scoped key** (*Create Query Report* permission), and the "
            "endpoint is edition/build-gated on some instances — always run the probe first.",
            "Prefer fixed, vetted query templates over exposing a free-form SQL box to end "
            "users; see the [connector README](../README.md#security-note)."],
        verified="Live-verified end to end on the demo (SELECT works, DML/catalog/GET "
                 "rejections confirmed).",
        refs=[EV_PHASE3,
              ("Template library (live-verified SQL)", "../../../templates/")]),
}

# --------------------------- sdp-cmdb-v1 -----------------------------------

V1_RESPONSE = """\
V1 responses are JSON with the legacy envelope
`{ "API": { "response": { "operation": { "result": {...}, "Details": ... } } } }`.
Success is `result.statuscode` **200** (with `result.status` `"Success"`); errors put the
reason in `result.message`. This is *not* the V3 `response_status` shape."""

CONTENT["sdp-cmdb-v1"] = {
    "ListAllCIs": entry(
        "Lists all configuration items via the **legacy V1 XML CMDB API** — for SDP builds "
        "**below 15100**, where CMDB V3 (and its relationships endpoint) does not exist. On "
        "15100+ prefer the *SDP – Assets & CMDB (v3)* connector.",
        response=V1_RESPONSE + "\n\nThe CI rows arrive under `Details`.",
        refs=[EV_PHASE2]),

    "CountAllCIs": entry(
        "Returns the total number of configuration items (legacy V1 API).",
        response=V1_RESPONSE + "\n\nThe count arrives under `Details`.",
        refs=[EV_PHASE2]),

    "GetCIRelationships": entry(
        "Gets all relationships of one CI, addressed **by CI name** (legacy V1 API).",
        params={"ci_name": "The configuration item's **name**, exactly as SDP shows it — "
                           "**case-sensitive**. (V1 addresses CIs by name, not ID.)"},
        response=V1_RESPONSE,
        gotchas=["The V1 API also supports filtering by relationship type and finding the "
                 "relationship **between two CIs** via sub-paths "
                 "(`cirelationships/{ci}/{relationship_type}`, `cirelationships/{ci}<->{other}`)"
                 " — not exposed as separate actions here because of the awkward path "
                 "characters; see the [connector README](../README.md).",
                 "On 15100+ builds (like the public demo) this endpoint is superseded by V3, "
                 "so it could not be live-verified there — verify on a real sub-15100 "
                 "instance."],
        verified=VERIFIED_MODELED),

    "ModifyCIRelationships": entry(
        "Adds **or** deletes CI relationships — the verb lives inside the XML payload, not "
        "the URL (legacy V1 API).",
        input_data="""## The `INPUT_DATA` payload — XML, not JSON

This is the one action in the family that takes **XML** (the V1 API predates the JSON
envelope). It travels as a form field; paste the document as one line or with line breaks —
both survive form-encoding.

### Formatting rules

- Keep the `<?xml version="1.0" encoding="UTF-8"?>` declaration.
- Escape XML specials inside CI names / values: `&` → `&amp;`, `<` → `&lt;`, `>` → `&gt;`.
- `relationshiptype` values must match your instance's relationship-type catalogue
  (via the Query connector, `templates/05-relationship-types.sql` lists them).
- CI names are **case-sensitive**, as everywhere in V1.

### Variation 1 — add a relationship

```xml
<?xml version="1.0" encoding="UTF-8"?>
<API version="1.0" locale="en">
  <records><relationships>
    <addrelationship>
      <toci>CI-A</toci>
      <relationshiptype>Depends on</relationshiptype>
      <relatedcis>
        <citype>Windows Server</citype>
        <ci><name>CI-B</name></ci>
      </relatedcis>
    </addrelationship>
  </relationships></records>
</API>
```

### Variation 2 — delete a relationship

```xml
<?xml version="1.0" encoding="UTF-8"?>
<API version="1.0" locale="en">
  <relationships>
    <deleterelationship>
      <fromci>CI-A</fromci>
      <relationshiptype>Depends on</relationshiptype>
      <relatedcis><ci>CI-B</ci></relatedcis>
    </deleterelationship>
  </relationships>
</API>
```

Note the asymmetry (it is the API's, not a typo): **add** nests under
`<records><relationships>` and names the far end `<toci>`; **delete** skips `<records>` and
uses `<fromci>`.""",
        params={"INPUT_DATA": "The XML relationship document — full templates below."},
        response=V1_RESPONSE,
        gotchas=["Write operation — test on a disposable instance only, never on the "
                 "read-only public demo."],
        verified="Modeled from a working V1 client and the official V1↔V3 comparison; "
                 "live-verify on a sub-15100 instance before relying on it (on 15100+ "
                 "builds, like the demo, V3 supersedes this endpoint)."),
}

# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def resolve_params(doc, op):
    out = []
    for p in op.get("parameters") or []:
        if "$ref" in p:
            name = p["$ref"].rsplit("/", 1)[-1]
            out.append(doc["parameters"][name])
        else:
            out.append(p)
    return out


def where(p):
    return {"path": "URL path", "query": "query string", "formData": "form field",
            "header": "header"}.get(p["in"], p["in"])


def first_sentence(text):
    text = (text or "").split(" Learn more: ")[0].strip()
    dot = text.find(". ")
    return text if dot < 0 else text[:dot + 1]


def schema_fields(doc, ref_name, depth=0):
    """Render the top-level fields of a definition as markdown bullets."""
    d = doc["definitions"].get(ref_name)
    if not d or "properties" not in d:
        return []
    lines = []
    for key, prop in d["properties"].items():
        if "$ref" in prop:
            target = prop["$ref"].rsplit("/", 1)[-1]
            lines.append(f"- `{key}` — {target.replace('Sdp', '')} object")
            continue
        typ = prop.get("type", "object")
        note = prop.get("description") or prop.get("x-ms-summary") or ""
        if typ == "array":
            item = prop.get("items", {})
            iref = item.get("$ref", "").rsplit("/", 1)[-1]
            sub = ""
            if iref and depth == 0:
                inner = doc["definitions"].get(iref, {}).get("properties", {})
                sub = " — items: " + ", ".join(f"`{k}`" for k in inner) if inner else ""
            lines.append(f"- `{key}` — array{sub}")
        else:
            lines.append(f"- `{key}` — {typ}" + (f" — {note}" if note else ""))
    return lines


def render_op(cname, doc, path, verb, op):
    info = doc["info"]
    opid = op["operationId"]
    c = CONTENT[cname].get(opid)
    if c is None:
        raise SystemExit(f"missing curated content: {cname}/{opid}")
    params = resolve_params(doc, op)
    endpoint = f"{verb.upper()} {doc.get('basePath', '')}{path}"
    v1 = cname == "sdp-cmdb-v1"

    md = [GENERATED_MARK, "", f"# {op['summary']}", ""]
    md.append(f"**Connector:** [{info['title']}](../README.md) (`{cname}`) · "
              f"**Action index:** [all actions](README.md)")
    md.append(f"**Endpoint:** `{endpoint}` · **Operation ID:** `{opid}`")
    md += ["", c["intro"], ""]

    # Parameters ------------------------------------------------------------
    md.append("## Parameters")
    md.append("")
    if params:
        md.append("| Designer label | Name | Where | Type | Required |")
        md.append("|---|---|---|---|---|")
        for p in params:
            label = p.get("x-ms-summary", p["name"])
            req = "yes" if p.get("required") else "no"
            md.append(f"| {label} | `{p['name']}` | {where(p)} | {p.get('type', 'string')} | {req} |")
        md.append("")
        for p in params:
            label = p.get("x-ms-summary", p["name"])
            md.append(f"### {label} (`{p['name']}`)")
            md.append("")
            if p["name"] == "Accept":
                md.append(ACCEPT_NOTE)
            elif p["name"] in c["params"]:
                md.append(c["params"][p["name"]])
            elif p["name"] in ("input_data", "INPUT_DATA"):
                md.append(first_sentence(p.get("description")) +
                          " Full format documented in the payload section below.")
            else:
                md.append(first_sentence(p.get("description")) or "See the table above.")
            md.append("")
    else:
        md.append("None — the URL (plus the connection's auth) is the entire call.")
        md.append("")

    # input_data deep dive ----------------------------------------------------
    if c["input_data"]:
        if not c["input_data"].lstrip().startswith("##"):
            md.append("## The `input_data` payload — formats and variations")
            md.append("")
        md.append(c["input_data"])
        md.append("")

    # Auth --------------------------------------------------------------------
    md.append(V1_AUTH if v1 else V3_AUTH)
    md.append("")

    # Response ------------------------------------------------------------------
    md.append("## Response")
    md.append("")
    ok_codes = [k for k in op.get("responses", {}) if k != "default"]
    ref = None
    for k in sorted(ok_codes):
        s = op["responses"][k].get("schema")
        if s and "$ref" in s:
            ref = s["$ref"].rsplit("/", 1)[-1]
            break
    if ref:
        md.append(f"Success ({'/'.join(sorted(ok_codes))}) returns the `{ref}` shape:")
        md.append("")
        md += schema_fields(doc, ref)
        md.append("")
    if c["response"]:
        md.append(c["response"])
        md.append("")
    if not v1:
        md.append(V3_RESPONSE_STATUS)
        md.append("")
    if v1:
        md.append("Anything else comes back on the `default` response — V1 failures put the "
                  "reason in `result.message`, and V3-style rejections can also appear.")
    else:
        md.append("Anything else comes back on the `default` response as the SDP error "
                  "envelope — surface `status_code` and `messages` in your flow's failure "
                  "branch.")
    md.append("")

    # Notes -----------------------------------------------------------------
    md.append("## Notes, limits & verification")
    md.append("")
    md.append(f"- {c['verified']}")
    for g in c["gotchas"]:
        md.append(f"- {g}")
    md.append("")

    # References --------------------------------------------------------------
    md.append("## References")
    md.append("")
    for label, url in c["refs"]:
        md.append(f"- [{label}]({url})")
    md.append(f"- [Connector README](../README.md) · [Repo README]({REPO}) · "
              f"[LESSONS.md](../../../LESSONS.md)")
    md.append("")
    return "\n".join(md)


def render_index(cname, doc, rows):
    info = doc["info"]
    md = [GENERATED_MARK, "", f"# {info['title']} — action docs", ""]
    md.append(f"One page per action of the [`{cname}`](../README.md) connector: every "
              "parameter explained, plus copy-paste `input_data` variations. These pages are "
              "the targets of each operation's **Learn more** link (`externalDocs` + the "
              "description suffix in the definition).")
    md += ["", "| Action | Operation ID | Endpoint | Doc |", "|---|---|---|---|"]
    for summary, opid, endpoint, fname in rows:
        md.append(f"| {summary} | `{opid}` | `{endpoint}` | [{fname}]({fname}) |")
    md.append("")
    return "\n".join(md)


def main():
    total = 0
    for cname in sorted(CONTENT):
        cdir = os.path.join(ROOT, "connectors", cname)
        doc = load(os.path.join(cdir, "apiDefinition.swagger.json"))
        ops = [(path, verb, op)
               for path, methods in doc["paths"].items()
               for verb, op in methods.items()]
        have = {op["operationId"] for _, _, op in ops}
        curated = set(CONTENT[cname])
        if have != curated:
            raise SystemExit(f"{cname}: content/spec drift — missing {sorted(have - curated)}, "
                             f"stale {sorted(curated - have)}")
        adir = os.path.join(cdir, "actions")
        os.makedirs(adir, exist_ok=True)
        rows = []
        for path, verb, op in ops:
            fname = kebab(op["operationId"]) + ".md"
            with open(os.path.join(adir, fname), "w", encoding="utf-8", newline="\n") as f:
                f.write(render_op(cname, doc, path, verb, op))
            rows.append((op["summary"], op["operationId"],
                         f"{verb.upper()} {doc.get('basePath', '')}{path}", fname))
            total += 1
        rows.sort(key=lambda r: r[3])
        with open(os.path.join(adir, "README.md"), "w", encoding="utf-8", newline="\n") as f:
            f.write(render_index(cname, doc, rows))
        print(f"{cname}: {len(rows)} action docs")
    print(f"total: {total} action docs")


if __name__ == "__main__":
    main()
